name: lovelense
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.4.0
  google_sign_in: ^6.2.2
  supabase_flutter: ^2.8.4
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  cloud_firestore: ^5.6.5
  image: ^4.5.4
  camera: ^0.11.1
  intl: ^0.20.2
  flutter_onboarding_slider: ^1.0.11
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1

dev_dependencies:s:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/service_account.json

    - assets/images/onboarding1.svg
    - assets/images/onboarding2.svg
    - assets/images/onboarding3.svg
    - assets/images/onboarding4.svg
    - assets/images/onboarding5.svg
    - assets/images/google_icon.png
    - assets/images/couple_image.png

